name: Test and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm ci --no-audit
      - run: npx tsc
      - run: docker build ./
      - name: Semantic release
        run: npx semantic-release
