name: Example

on: push

jobs:
  version:
    name: Determine next release version
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Determine next release version
        uses: bifravst/get-next-version-action@saga
        id: version
        with:
          branch: saga

      - run: |
          NEXT_VERSION=${{ steps.version.outputs.nextRelease }}
          echo ${NEXT_VERSION}
